name: Build & Push Docker Images

on:
  push:
    branches: [ main, beta ]   # build on pushes to these branches
  workflow_dispatch: {}        # allow manual runs

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed for GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Auto-generate tags for both registries
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jermcee/plex-notifier
            ghcr.io/jjermany/plex-notifier
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=raw,value=beta,enable=${{ github.ref == 'refs/heads/beta' }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
